reworked creation script for update service

diff --git a/create_service.in b/create_service.in
--- a/create_service.in
+++ b/create_service.in
@@ -1,6 +1,9 @@
 #!/bin/sh
 #
 # $Log: create_service.in,v $
+# Revision 1.29  2021-05-01 13:15:37+05:30  Cprogrammer
+# reworked service creation for update service
+#
 # Revision 1.28  2021-04-30 21:37:14+05:30  Cprogrammer
 # fixed QMAILQUEUE for root user
 #
@@ -87,7 +90,7 @@
 # Initial revision
 #
 #
-# $Id: create_service.in,v 1.28 2021-04-30 21:37:14+05:30 Cprogrammer Exp mbhangui $
+# $Id: create_service.in,v 1.29 2021-05-01 13:15:37+05:30 Cprogrammer Exp mbhangui $
 #
 
 check_update_if_diff()
@@ -141,52 +144,38 @@ add_service()
 			"ucspi-tcp mpdev libqmail indimail-mini mpd"
 		check_update_if_diff $servicedir/$service_name/variables/INTERVAL 21600
 		check_update_if_diff $servicedir/$service_name/variables/DEBIAN_FRONTEND "noninteractive"
-		home=$(getent passwd 1000|cut -d: -f6)
-		if [ -n "$home" ] ; then
-			check_update_if_diff $servicedir/$service_name/variables/HOME $home
-		fi
-		if [ -f /usr/sbin/qmail-direct ] ; then
-			# user 1000
-			user=$(getent passwd 1000|cut -d: -f1)
-			if [ -n "$user" ] ; then
+		for i in 1000 root alias
+		do
+			user=$(getent passwd $i|cut -d: -f1)
+			uid=$(getent passwd $i|cut -d: -f3)
+			gid=$(getent passwd $i|cut -d: -f4)
+			home=$(getent passwd $i|cut -d: -f6)
+			if [ -z "$user" -o -z "$home" -o -z "$uid" -o -z "$gid" ] ; then
+				echo "unable to get passwd entry for $i" 1>&2
+				continue
+			fi
+			if [ "$i" = "1000" ] ; then
+				check_update_if_diff $servicedir/$service_name/variables/HOME $home
 				check_update_if_diff $servicedir/$service_name/variables/LOGNAME $user
+			fi
+			mkdir -p $home/Maildir/new
+			mkdir -p $home/Maildir/cur
+			mkdir -p $home/Maildir/tmp
+			chown -R $uid:$gid $home/Maildir
+			if [ ! "$i" = "1000" -a ! "$i" = "root" ] ; then
+				continue
+			fi
+			if [ -f /usr/sbin/qmail-direct ] ; then
 				grep -w $user /etc/indimail/control/direct_mail_users >/dev/null 2>&1
 				if [ $? -ne 0 ] ; then
 					echo $user >> /etc/indimail/control/direct_mail_users
 				fi
-			fi
-			if [ -n "$home" ] ; then
 				mkdir -p $home/.defaultqueue
 				if [ ! -f $home/.defaultqueue/QMAILQUEUE ] ; then
 					check_update_if_diff $home/.defaultqueue/QMAILQUEUE "/usr/sbin/qmail-direct"
 				fi
-				mkdir -p $home/Maildir/new
-				mkdir -p $home/Maildir/cur
-				mkdir -p $home/Maildir/tmp
-				gid=$(getent passwd 1000|cut -d: -f4)
-				if [ -n "$gid" ] ; then
-					chown -R 1000:"$gid" $home/Maildir
-				else
-					chown -R 1000:1000 $home/Maildir
-				fi
 			fi
-
-			# user root
-			home=$(getent passwd root|cut -d: -f6)
-			mkdir -p $home/.defaultqueue
-			check_update_if_diff $home/.defaultqueue/QMAILQUEUE "/usr/sbin/qmail-direct"
-
-			# user alias
-			home=$(getent passwd alias|cut -d: -f6)
-			uid=$(getent passwd alias|cut -d: -f3)
-			gid=$(getent passwd alias|cut -d: -f4)
-			if [ -n "$home" ] ; then
-				mkdir -p $home/Maildir/new
-				mkdir -p $home/Maildir/cur
-				mkdir -p $home/Maildir/tmp
-				chown -R "$uid":"$gid" $home/Maildir
-			fi
-		fi
+		done
 	fi
 	if [ " $service_name" = " fclient" ] ; then
 		(
@@ -281,7 +270,8 @@ add_service()
 		echo "    echo \\\"checking updates for \$UPDATE\\\""
 		case "$system" in
 			debian)
-			echo "    apt-get -qy update"
+		check_update_if_diff $servicedir/$service_name/variables/DEBIAN_FRONTEND "noninteractive"
+			echo "    env DEBIAN_FRONTEND=noninteractive apt-get -qy update"
 			echo "    list=\\\$(apt list --upgradable \$UPDATE|grep -v List|wc -l)"
 			;;
 			rpm-dnf)
@@ -312,7 +302,8 @@ add_service()
 		echo "    elif [ -x /usr/bin/at ] ; then"
 		case "$system" in
 			debian)
-			echo "      echo \\\"apt-get -qy --only-upgrade install \$UPDATE\\\"|at now +1 minute"
+			echo -n "      echo \\\"env DEBIAN_FFRONTEND=noninteractive apt-get "
+			echo    "-qy --only-upgrade install \$UPDATE\\\"|at now +1 minute"
 			;;
 			rpm-dnf)
 			echo "      echo \\\"dnf update \$UPDATE\\\"|at now +1 minute"
@@ -327,7 +318,7 @@ add_service()
 		echo "    else"
 		case "$system" in
 			debian)
-			echo "      apt-get -qy --only-upgrade install \$UPDATE"
+			echo "      env DEBIAN_FFRONTEND=noninteractive apt-get -qy --only-upgrade install \$UPDATE"
 			;;
 			rpm-dnf)
 			echo "      dnf update \$UPDATE"
@@ -384,7 +375,7 @@ fi
 logdir=/var/log/svc
 servicedir=/service
 prog_args="$0 $*"
-RCSID="# \$Id: create_service.in,v 1.28 2021-04-30 21:37:14+05:30 Cprogrammer Exp mbhangui $"
+RCSID="# \$Id: create_service.in,v 1.29 2021-05-01 13:15:37+05:30 Cprogrammer Exp mbhangui $"
 while test $# -gt 0; do
 	case "$1" in
 	-*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
