bug fixes

diff --git a/create_service.in b/create_service.in
--- a/create_service.in
+++ b/create_service.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: create_service.in,v 1.46 2022-06-30 15:42:28+05:30 Cprogrammer Exp mbhangui $
+# $Id: create_service.in,v 1.47 2022-06-30 16:38:52+05:30 Cprogrammer Exp mbhangui $
 #
 
 check_update_if_diff()
@@ -19,39 +19,52 @@ get_mpd_conf_value()
 
 add_service()
 {
-	if [ "$service_name" != " rsync" -a $# -ne 3 ] ; then
-		(
-		echo "USAGE: create_service --servicedir=path --user=username \\"
-		echo "  --host=host --port=port --add-service"
-		echo "  --service_name=fclient|fserver|update|rsync \\"
-		echo "  --add-service"
-		echo
-		) 1>&2
-		return 1
-	elif [ "$service_name" = " rsync" -a $# -ne 2 ] ; then
+	if [ "$service_name" = "fclient" -o "$service_name" = "fserver" ] ; then
+		if [ $# -ne 3 ] ; then
+			(
+			echo "USAGE: create_service --servicedir=path --user=username \\"
+			echo "  --host=host --port=port"
+			echo "  --service_name=fclient|fserver \\"
+			echo "  --add-service"
+			echo
+			) 1>&2
+			return 1
+		fi
+		host=$1
+		port=$2
+		userid=$3
+	elif [ "$service_name" = "update" ] ; then
+		if [ $# -ne 1 ] ; then
+			(
+			echo "USAGE: create_service --servicedir=path \\"
+			echo "  --service_name=update --add-service"
+			echo
+			) 1>&2
+			return 1
+		fi
+		userid=$1
+	elif [ "$service_name" = "rsync" -a $# -ne 0 ] ; then
 		(
 		echo "USAGE: create_service --servicedir=path \\"
-		echo "  --host=host --port=port --add-service"
-		echo "  --service_name=fclient|fserver|update|rsync \\"
-		echo "  --add-service"
+		echo "  --host=host --port=port"
+		echo "  --service_name=rsync --add-service"
 		echo
 		) 1>&2
 		return 1
-	fi
-	host=$1
-	port=$2
-	if [ $# -eq 3 ] ; then
-		userid=$3
 	fi
 	case "$SYSTEM" in
 		Linux)
-		user=$(getent passwd $userid 2>/dev/null| cut -d: -f1)
-		if [ $? -ne 0 ] ; then
-			if [ $? -eq 2 ] ; then
+		user=$(getent passwd $userid)
+		status=$?
+		if [ $status -ne 0 ] ; then
+			if [ $status -eq 2 ] ; then
 				echo "No such userid $userid" 1>&2
-				return 1
+			else
+				echo "failed to get information for user $userid" 1>&2
 			fi
 			return 1
+		else
+			user=$(echo $user|cut -d: -f1)
 		fi
 		;;
 		Darwin)
@@ -106,17 +119,30 @@ add_service()
 		elif [ "$service_name" = "update" ] ; then
 			check_update_if_diff $servicedir/$service_name/variables/HOME "$home"
 		fi
+	elif [ "$service_name" = "fclient" -o "$service_name" = "update" ] ; then
+		echo "failed to get home for $user" 1>&2
+		return 1
 	fi
-	case "$SYSTEM" in
-		Linux)
-		t_uid=$(getent passwd $user|cut -d: -f3)
-		t_gid=$(getent passwd $user|cut -d: -f4)
-		;;
-		Darwin)
-		t_uid=$(dscl . -read /Users/$user UniqueID|cut -d: -f2|sed 's{ {{g')
-		t_gid=$(dscl . -read /Users/$user PrimaryGroupID|cut -d: -f2|sed 's{ {{g')
-		;;
-	esac
+	if [ "$service_name" != "rsync" ] ; then
+		case "$SYSTEM" in
+			Linux)
+			t_uid=$(getent passwd $user|cut -d: -f3)
+			t_gid=$(getent passwd $user|cut -d: -f4)
+			if [ -z "$t_uid" -o -z "$t_gid" ] ; then
+				echo "failed to get uid/gid for $user" 1>&2
+				return 1
+			fi
+			;;
+			Darwin)
+			t_uid=$(dscl . -read /Users/$user UniqueID|cut -d: -f2|sed 's{ {{g')
+			t_gid=$(dscl . -read /Users/$user PrimaryGroupID|cut -d: -f2|sed 's{ {{g')
+			if [ -z "$t_uid" -o -z "$t_gid" ] ; then
+				echo "failed to get uid/gid for $user" 1>&2
+				return 1
+			fi
+			;;
+		esac
+	fi
 	if [ "$service_name" = "fclient" ] ; then
 		mkdir -p $home/.pistop
 		for i in pistopstart
@@ -181,10 +207,6 @@ add_service()
 
 		# Create Maildir for receiving mail
 
-		if [ -z "$home" -o -z "$t_uid" -o -z "$t_gid" ] ; then
-			echo "unable to get passwd entry for $i" 1>&2
-			continue
-		fi
 		if [ ! -d $home/Malidir ] ; then
 			mkdir -p $home/Maildir/new
 			mkdir -p $home/Maildir/cur
@@ -467,7 +489,7 @@ prog_args="$0 $*"
 SYSTEM=$(uname -s)
 music_dir=$(get_mpd_conf_value music_dir)
 MDRIVE=$(dirname $music_dir)
-RCSID="# \$Id: create_service.in,v 1.46 2022-06-30 15:42:28+05:30 Cprogrammer Exp mbhangui $"
+RCSID="# \$Id: create_service.in,v 1.47 2022-06-30 16:38:52+05:30 Cprogrammer Exp mbhangui $"
 while test $# -gt 0; do
 	case "$1" in
 	-*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
@@ -524,6 +546,9 @@ while test $# -gt 0; do
 done
 #
 # $Log: create_service.in,v $
+# Revision 1.47  2022-06-30 16:38:52+05:30  Cprogrammer
+# fixed bugs
+#
 # Revision 1.46  2022-06-30 15:42:28+05:30  Cprogrammer
 # version 2.0 of create_service
 #
